# Generated by Django 3.2 on 2022-04-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('Website', models.URLField(blank=True, max_length=250, null=True)),
                ('adress', models.CharField(blank=True, max_length=250, null=True)),
                ('responsible_person', models.CharField(blank=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('company_type', models.CharField(blank=True, choices=[('CL', 'client'), ('F', 'fournisseur'), ('P', 'partenaire'), ('CN', 'concurrent'), ('LD', 'Lead')], max_length=2, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('EC', 'e-commerce'), ('WS', 'web site'), ('WA', 'web app')], max_length=2, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/')),
                ('collab_start', models.DateField(blank=True, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('EC', 'e-commerce'), ('WS', 'web site'), ('WA', 'web app')], max_length=2, null=True)),
                ('status', models.CharField(blank=True, choices=[('I', 'inrested'), ('CA', 'call again'), ('NI', 'not intrested')], max_length=2, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('decision', models.CharField(blank=True, choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], max_length=2, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('EC', 'e-commerce'), ('WS', 'web site'), ('WA', 'web app')], max_length=2, null=True)),
                ('collab_start', models.DateField(blank=True, null=True)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.company')),
            ],
        ),
    ]
