# Generated by Django 3.2 on 2022-05-21 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20220427_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='Website',
            new_name='website',
        ),
    ]
