# Generated by Django 3.2 on 2022-05-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_website_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('CL', 'client'), ('F', 'fournisseur'), ('P', 'partenaire'), ('CN', 'concurrent')], max_length=2, null=True),
        ),
    ]
