# Generated by Django 3.2 on 2022-05-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
