# Generated by Django 3.2 on 2022-05-24 13:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20220506_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
