# Generated by Django 3.2 on 2022-04-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('project_type', models.CharField(blank=True, choices=[('EC', 'e-commerce'), ('WS', 'web site'), ('WA', 'web app')], max_length=2, null=True)),
                ('contract', models.CharField(blank=True, choices=[('H', 'hosting'), ('A', 'annual'), ('S', 'semi-anuual'), ('Q', 'quarterly'), ('AD', 'adverisement')], max_length=2, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('CO', 'confirm'), ('CP', 'completed'), ('PE', 'pending'), ('CL', 'cancelled')], max_length=2, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.company')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.employee')),
            ],
        ),
    ]
