# Generated by Django 3.2 on 2022-05-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.CharField(blank=True, choices=[('H', 'hosting'), ('A', 'annual'), ('S', 'semi-annual'), ('Q', 'quarterly'), ('AD', 'adverisement')], max_length=2, null=True),
        ),
    ]
