# Generated by Django 3.2 on 2022-05-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
