# Generated by Django 3.2 on 2022-05-26 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '__first__'),
        ('contact', '0007_alter_lead_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0005_alter_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='contact.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('CO', 'Confirm'), ('CP', 'Completed'), ('PE', 'Pending'), ('CA', 'Cancelled')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_type', models.CharField(choices=[('PA', 'paiement'), ('SA', 'salaire '), ('CR', 'creance'), ('CH', 'charges'), ('AL', 'allouer')], max_length=2, null=True)),
                ('other', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashflow.account')),
                ('made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_transactions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='project.project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('CO', 'Confirm'), ('CP', 'Completed'), ('PE', 'Pending'), ('CA', 'Cancelled')], max_length=2, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('actif', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.project')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
