# Generated by Django 3.2 on 2022-05-26 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20220526_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('CF', 'Confirm'), ('CP', 'Completed'), ('PE', 'Pending'), ('CA', 'Cancelled')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('CF', 'Confirm'), ('CP', 'Completed'), ('PE', 'Pending'), ('CA', 'Cancelled')], max_length=2, null=True),
        ),
    ]
