# Generated by Django 3.2 on 2022-05-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_lead_note'),
        ('project', '0007_auto_20220526_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='contact.company', verbose_name='client'),
            preserve_default=False,
        ),
    ]
