# Generated by Django 3.2 on 2022-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20220526_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_type',
            field=models.CharField(blank=True, choices=[('PA', 'paiement'), ('SA', 'salaire '), ('CR', 'creance'), ('CH', 'charges'), ('AL', 'allouer')], max_length=2, null=True),
        ),
    ]
